# Generated by Django 5.0.2 on 2024-05-05 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0003_alter_product_name'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_SALE', 'On Sale'), ('OUT_OF_STOCK', 'Out of Stock')], default='AVAILABLE', max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default='1'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('ON_CART', 'On Cart'), ('TO_PAY', 'To Pay'), ('TO_SHIP', 'To Ship'), ('TO_RECEIVE', 'To Receive'), ('DELIVERED', 'Delivered')], max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='user_management.profile')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchstore.product')),
            ],
        ),
    ]
