# Generated by Django 5.0.3 on 2024-03-21 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Comment", new_name="Comments",),
        migrations.RenameModel(old_name="Commission", new_name="Commissions",),
    ]
