# Generated by Django 5.0.2 on 2024-03-18 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Created_on',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Entry',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Updated_on',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='articlecategory',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='articlecategory',
            old_name='Name',
            new_name='name',
        ),
    ]
